services:
  class-room:
    image: juantiradoboza/api-class-room:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:8080"
    environment:
      PORT: ${PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_DB: ${SERVER_DB}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      AZURE_CONNECTION: ${AZURE_CONNECTION}
      CONTAINER_NAME: ${CONTAINER_NAME}

    restart: unless-stopped
