spring:
  application:
    name: virtual-classroom

  datasource:
    url: jdbc:postgresql://localhost:5432/db_virtual_classroom
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    clean-disabled: false

server:
  port: ${PORT}

application:
  security:
    jwt:
      secret-key: McvbIKwPavjhmKBwFUdHDXzvfWeAZgaJ8XJr6cBsvNkPI9VUVAwW7GzFMV6ZhHsI
      expiration: 15000
      refresh-token:
        expiration: 2592000000

azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=cresources01;AccountKey=CRJxn8fwi0s0uP+xGkv4FFA0jM8Vti5lRsNuNgEhx5BSrCKUtjwAnHiF9po015y5gyFLQ4pUbv4n+AStxMqINA==;EndpointSuffix=core.windows.net
    container-name: archivos-app