
spring:
  application:
    name: virtual-classroom
  datasource:
    url: jdbc:postgresql://localhost:5432/db_virtual_classroom
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    clean-disabled: false
    clean-on-validation-error: true

server:
  port: ${PORT}