spring:
  application:
    name: virtual-classroom

  datasource:
    url: jdbc:postgresql://classroom.postgres.database.azure.com:5432/mydb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 15000
      refresh-token:
        expiration: 2592000000

azure:
  storage:
    connection-string: ${AZURE_CONNECTION}
    container-name: ${CONTAINER_NAME}